### ISSUE TITLE
Provider does not recognize format extension variant: jpg ~ jpeg

### ISSUE THREAD

**Issue by ambroisemaupate** [rezozero/intervention-request-provider#2]
![image](https://github.com/rezozero/intervention-request-provider/assets/380026/0824514b-7bd8-4b94-9625-1672815351c4)

If format is `jpeg`, provider do not test if image path ends with `jpe?g` (jpg, jpeg) and ends up with a 404 path.

`/e85a5f20/fullwidth.jpg` will be transformed to `/e85a5f20/fullwidth.jpg.jpeg` because format is `jpeg` and not `jpg`

**Comment by manuelodelain** [comment]
Resolved with 91c684d6234fbbe21f8c49e3022b9cbea024ba51
